export const questionairesConstants = {
    QUESTION_SUBMIT_REQUEST: 'QUESTION_SUBMIT_REQUEST',
    QUESTION_SUBMIT_SUCCESS: 'QUESTION_SUBMIT_SUCCESS',
    QUESTION_SUBMIT_FAILURE: 'QUESTION_SUBMIT_FAILURE',

    QUESTION_GETALL_REQUEST: 'QUESTION_GETALL_REQUEST',
    QUESTION_GETALL_SUCCESS: 'QUESTION_GETALL_SUCCESS',
    QUESTION_GETALL_FAILURE: 'QUESTION_GETALL_FAILURE',

    QUESTION_EDIT_REQUEST: 'QUESTION_EDIT_REQUEST',
    QUESTION_EDIT_SUCCESS: 'QUESTION_EDIT_SUCCESS',
    QUESTION_EDIT_FAILURE: 'QUESTION_EDIT_FAILURE',

    QUESTION_DELETE_REQUEST: 'QUESTION_DELETE_REQUEST',
    QUESTION_DELETE_SUCCESS: 'QUESTION_DELETE_SUCCESS',
    QUESTION_DELETE_FAILURE: 'QUESTION_DELETE_FAILURE',

    QUESTIONS_DELETE_REQUEST: 'QUESTIONS_DELETE_REQUEST',
    QUESTIONS_DELETE_SUCCESS: 'QUESTIONS_DELETE_SUCCESS',
    QUESTIONS_DELETE_FAILURE: 'QUESTIONS_DELETE_FAILURE',
};

