export const modalConstants = {
    ADD_QUESTION: 'ADD_QUESTION',
    EDIT_QUESTION: 'EDIT_QUESTION',
    DELETE_QUESTION: 'DELETE_QUESTION',
    DELETE_ALL_QUESTIONS: 'DELETE_ALL_QUESTIONS',
    HIDE_MODAL: 'HIDE_MODAL',
};
